module(
    name = "android_mms",
    version = "0.0.1",
)

bazel_dep(name = "rules_java", version = "8.11.0")
bazel_dep(name = "rules_jvm_external", version = "6.7")

maven_android_mms = use_extension("@rules_jvm_external//:extensions.bzl", "maven")

maven_android_mms.install(
    name = "maven_android_mms",
    artifacts = [
        "org.slf4j:slf4j-api:1.7.26",
    ],
    repositories = [
        "https://repo1.maven.org/maven2/",
        "https://jcenter.bintray.com/",
        "https://maven.google.com",
        "https://repository.jboss.org/nexus/content/repositories/releases/",
        "https://repository.jboss.org",
    ],
)

use_repo(maven_android_mms, "maven_android_mms")
